"use client";

import { useState, useEffect } from "react";
import QRCode from "qrcode";
import { Download, Printer, QrCode, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { getPlotQrUrl } from "@/lib/plot-urls";

/**
 * Plot QR codes. Each plot's QR encodes the plot's internal URL —
 * because the plot's database ID is permanent (assigned at creation,
 * never changes), the QR is effectively a fixed identity that's
 * good for the life of the plot. No need to "generate" or store
 * anything — the QR is a deterministic function of the plot ID.
 *
 * Keith May 2026: "i want these autogenerated not generated on
 * request so when a plot is created just create a QR and keep it
 * fixed to that plot forever". This module renders QRs immediately
 * on mount with no button click — the data was always permanent,
 * the lazy generation was just a UX wart.
 */

interface PlotQRCodeProps {
  plotId: string;
  plotNumber: string | null;
  plotName: string;
  siteId: string;
  siteName: string;
}

export function PlotQRCode({
  plotId,
  plotNumber,
  plotName,
  siteId,
  siteName,
}: PlotQRCodeProps) {
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!plotId || !siteId) return;
    // (May 2026 pattern sweep) Cancellation flag — switching plots
    // rapidly could land the previous plot's QR data URL.
    let cancelled = false;
    const url = getPlotQrUrl({ siteId, plotId });
    QRCode.toDataURL(url, {
      width: 256,
      margin: 2,
      color: { dark: "#000000", light: "#ffffff" },
      errorCorrectionLevel: "M",
    })
      .then((d) => { if (!cancelled) setQrDataUrl(d); })
      .catch(console.error);
    return () => { cancelled = true; };
  }, [plotId, siteId]);

  const handleDownload = () => {
    if (!qrDataUrl) return;
    const link = document.createElement("a");
    link.download = `QR-Plot-${plotNumber || plotName}.png`;
    link.href = qrDataUrl;
    link.click();
  };

  const handlePrint = () => {
    if (!qrDataUrl) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html>
        <head><title>QR Code - Plot ${plotNumber || plotName}</title></head>
        <body style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;margin:0;">
          <h2 style="margin-bottom:4px;">${siteName}</h2>
          <h3 style="margin-top:0;color:#666;">Plot ${plotNumber || plotName}</h3>
          <img src="${qrDataUrl}" style="width:300px;height:300px;" />
          <p style="color:#999;font-size:12px;margin-top:8px;">Scan to open plot details</p>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2 text-sm">
          <QrCode className="size-4" />
          QR Code
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col items-center gap-3">
          {qrDataUrl ? (
            <>
              <img
                src={qrDataUrl}
                alt={`QR Code for Plot ${plotNumber || plotName}`}
                className="size-40 rounded border"
              />
              <p className="text-xs text-muted-foreground">
                Scan to open plot details
              </p>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={handleDownload}>
                  <Download className="mr-1 size-3.5" />
                  Download
                </Button>
                <Button variant="outline" size="sm" onClick={handlePrint}>
                  <Printer className="mr-1 size-3.5" />
                  Print
                </Button>
              </div>
            </>
          ) : (
            <Loader2 className="size-6 animate-spin text-muted-foreground" />
          )}
        </div>
      </CardContent>
    </Card>
  );
}

// ─── Batch QR for the Site Admin → QR Codes tab ──────────────────────

interface BatchQRProps {
  siteId: string;
  siteName: string;
  plots: Array<{
    id: string;
    plotNumber: string | null;
    name: string;
    houseType: string | null;
  }>;
}

export function BatchPlotQR({ siteId, siteName, plots }: BatchQRProps) {
  // Auto-render every QR on mount. Each plot's QR is a deterministic
  // function of the plot ID — they're "auto-generated" by virtue of
  // existing. No button click required.
  const [qrCodes, setQrCodes] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [downloadingAll, setDownloadingAll] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const codes: Record<string, string> = {};
      for (const plot of plots) {
        try {
          const url = getPlotQrUrl({ siteId, plotId: plot.id });
          codes[plot.id] = await QRCode.toDataURL(url, {
            width: 256,
            margin: 1,
            errorCorrectionLevel: "M",
          });
        } catch (e) {
          console.error(`QR error for plot ${plot.id}:`, e);
        }
      }
      if (!cancelled) {
        setQrCodes(codes);
        setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [siteId, plots]);

  const printAll = () => {
    const win = window.open("", "_blank");
    if (!win) return;

    const plotsHtml = plots
      .map(
        (plot) => `
        <div style="display:inline-flex;flex-direction:column;align-items:center;padding:16px;border:1px solid #eee;margin:8px;border-radius:8px;width:220px;page-break-inside:avoid;">
          ${qrCodes[plot.id] ? `<img src="${qrCodes[plot.id]}" style="width:160px;height:160px;" />` : ""}
          <p style="font-weight:bold;margin:8px 0 0;">Plot ${plot.plotNumber || plot.name}</p>
          ${plot.houseType ? `<p style="color:#666;font-size:12px;margin:2px 0;">${plot.houseType}</p>` : ""}
          <p style="color:#999;font-size:10px;margin:4px 0 0;">${siteName}</p>
        </div>
      `,
      )
      .join("");

    win.document.write(`
      <html>
        <head><title>QR Codes - ${siteName}</title></head>
        <body style="font-family:sans-serif;padding:20px;">
          <h2>${siteName} — Plot QR Codes</h2>
          <div style="display:flex;flex-wrap:wrap;">${plotsHtml}</div>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  // Print or download a single plot's QR. Same body as the single-card
  // PlotQRCode handlers, inlined here so each tile in the grid has its
  // own quick actions.
  const printOne = (plotId: string, plotLabel: string, houseType: string | null) => {
    const code = qrCodes[plotId];
    if (!code) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html>
        <head><title>QR Code - ${plotLabel}</title></head>
        <body style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;margin:0;">
          <h2 style="margin-bottom:4px;">${siteName}</h2>
          <h3 style="margin-top:0;color:#666;">${plotLabel}</h3>
          ${houseType ? `<p style="color:#999;margin:0 0 8px;">${houseType}</p>` : ""}
          <img src="${code}" style="width:300px;height:300px;" />
          <p style="color:#999;font-size:12px;margin-top:8px;">Scan to open plot details</p>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  const downloadOne = (plotId: string, plotLabel: string) => {
    const code = qrCodes[plotId];
    if (!code) return;
    const link = document.createElement("a");
    link.download = `QR-${plotLabel.replace(/\s+/g, "_")}.png`;
    link.href = code;
    link.click();
  };

  // Bundle every QR PNG into a single ZIP for plotting / posting.
  const downloadAll = async () => {
    if (Object.keys(qrCodes).length === 0) return;
    setDownloadingAll(true);
    try {
      // jszip on the client — lighter than archiver and works in-browser.
      // Lazy import so unused on the single-plot view.
      const JSZip = (await import("jszip")).default;
      const zip = new JSZip();
      for (const plot of plots) {
        const code = qrCodes[plot.id];
        if (!code) continue;
        const base64 = code.split(",")[1] ?? "";
        const label = `Plot_${plot.plotNumber || plot.name}`;
        zip.file(`${label.replace(/\s+/g, "_")}.png`, base64, { base64: true });
      }
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `QR-Codes-${siteName.replace(/\s+/g, "_")}.zip`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } finally {
      setDownloadingAll(false);
    }
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center justify-between text-sm">
          <span className="flex items-center gap-2">
            <QrCode className="size-4" />
            Plot QR Codes ({plots.length})
          </span>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={downloadAll}
              disabled={loading || downloadingAll || Object.keys(qrCodes).length === 0}
            >
              {downloadingAll ? (
                <Loader2 className="mr-1 size-3.5 animate-spin" />
              ) : (
                <Download className="mr-1 size-3.5" />
              )}
              Download all (ZIP)
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={printAll}
              disabled={loading || Object.keys(qrCodes).length === 0}
            >
              <Printer className="mr-1 size-3.5" />
              Print all
            </Button>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="flex items-center justify-center py-8 text-muted-foreground">
            <Loader2 className="size-5 animate-spin" />
          </div>
        ) : plots.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No plots on this site yet.
          </p>
        ) : (
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
            {plots.map((plot) => {
              const label = plot.plotNumber ? `Plot ${plot.plotNumber}` : plot.name;
              return (
                <div
                  key={plot.id}
                  className="group flex flex-col items-center rounded-lg border bg-white p-2"
                >
                  {qrCodes[plot.id] && (
                    <img
                      src={qrCodes[plot.id]}
                      alt={`QR ${label}`}
                      className="size-28"
                    />
                  )}
                  <p className="mt-1 text-center text-xs font-medium">{label}</p>
                  {plot.houseType && (
                    <p className="text-[10px] text-muted-foreground">
                      {plot.houseType}
                    </p>
                  )}
                  <div className="mt-2 flex gap-1 opacity-0 transition-opacity group-hover:opacity-100">
                    <button
                      type="button"
                      onClick={() => printOne(plot.id, label, plot.houseType)}
                      className="rounded p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700"
                      title="Print this QR"
                    >
                      <Printer className="size-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={() => downloadOne(plot.id, label)}
                      className="rounded p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700"
                      title="Download this QR"
                    >
                      <Download className="size-3.5" />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
